[project]
name = "wechat-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.104.1",
    "psutil==5.9.6",
    "pydantic==2.5.0",
    "uvicorn[standard]==0.24.0",
]
